[versions]
agp = "8.13.2"
android-compileSdk = "36"
android-minSdk = "23"
android-targetSdk = "36"
androidx-activity = "1.12.2"
androidx-appcompat = "1.7.1"
androidx-core = "1.17.0"
#androidx-espresso = "3.7.0"
androidx-lifecycle = "2.10.0-alpha07"
#androidx-testExt = "1.3.0"
componentsResources = "1.10.0"
composeMultiplatform = "1.10.0"
#junit = "4.13.2"
foundation = "1.10.0"
kotlin = "2.3.0"
material3 = "1.10.0-alpha05"
maven-publish = "0.36.0"
firebaseStorageKtx = "21.0.2"
ktor = "3.4.0"
runtime = "1.10.0"
startupRuntime = "1.2.0"
kotlinxCoroutinesCore = "1.10.2"
filekit = "0.12.0"
kdownloadFile = "2.5.1"
kfirebaseCore = "2.1.1"
uiTooling = "1.10.0"
uiToolingPreview = "1.10.0"
urlencoderLib = "1.6.0"
#runner = "1.7.0"
core = "1.7.0"
firebaseBom = "34.4.0"

[libraries]
components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "componentsResources" }
foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "foundation" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-testJunit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-lifecycle-viewmodelCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtimeCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }
androidx-startup-runtime = { module = "androidx.startup:startup-runtime", version.ref = "startupRuntime" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
firebase-storage-ktx = { group = "com.google.firebase", name = "firebase-storage-ktx", version.ref = "firebaseStorageKtx" }
material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "material3" }
runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "runtime" }
ui-tooling = { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "uiTooling" }
ui-tooling-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "uiToolingPreview" }
urlencoder-lib = { module = "net.thauvin.erik.urlencoder:urlencoder-lib", version.ref = "urlencoderLib" }
filekit-dialogs-compose = { module = "io.github.vinceglb:filekit-dialogs-compose", version.ref = "filekit" }
filekit-dialogs = { module = "io.github.vinceglb:filekit-dialogs", version.ref = "filekit" }
filekit-core = { module = "io.github.vinceglb:filekit-core", version.ref = "filekit" }
firebase-storage = { module = "com.google.firebase:firebase-storage" }
kdownload-file = { module = "io.github.the-best-is-best:kdownload-file", version.ref = "kdownloadFile" }
kfirebase-core = { module = "io.github.the-best-is-best:kfirebase-core", version.ref = "kfirebaseCore" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
androidx-core = { group = "androidx.test", name = "core", version.ref = "core" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }